### ISSUE TITLE
Record video doesn't work

### ISSUE THREAD

**Issue by SylvanoTombo** [Avishaidev/camera-preview-video#1]
Record video doesn't work , it say plugin cordova not installed

**Comment by Avishaidev** [comment]
did you install it as write on docs?

**Comment by Avishaidev** [comment]
ionic cordova plugin add "PATH/TO/PROJECT/DIR"/myPlugin/cordova-plugin-camera-preview

**Comment by SylvanoTombo** [comment]
yes..I have already followed the docs.

**Comment by SylvanoTombo** [comment]
the image capture work but the video not.

**Comment by Avishaidev** [comment]
Whar error you got when record video?

בתאריך יום ג׳, 19 במרץ 2019, 10:00, מאת SylvanoTombo ‏<
notifications@github.com>:

**Comment by SylvanoTombo** [comment]
it say: Ionic Native: tried calling CameraPreview.startRecordVideo, but the CameraPreview plugin is not installed

startRecordVideo: err plugin not installed

**Comment by teeban10** [comment]
Same problem with me, any solution ?

**Comment by Avishaidev** [comment]
Plugin files are update, Install again the plugin from this repository and check.
