### ISSUE TITLE
Integrate this project in ionic 4

### ISSUE THREAD

**Issue by aamez227** [Avishaidev/camera-preview-video#6]
How could I integrate this project in ionic 4...?

**Comment by SylvanoTombo** [comment]
Hi @aamez227, I think this plugin have an installation steps.

**Comment by aamez227** [comment]
> Hi @aamez227, I think this plugin have an installation steps.

Since you have use params and send the data to camera-preview page, in ionic 4 it is giving error...

**Comment by aamez227** [comment]
done
